services:
  mongo:
    container_name: mongo
    env_file:
      - .env.local
    build:
      context: ./mongo
      args:
        MONGO_VERSION: '8.0.13'
    environment:
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: ${DB_PORT}
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: 'mongosh'
    volumes:
      - mongo-data:/data/db
    ports:
      - '${DB_PORT}:${DB_PORT}'
    restart: unless-stopped
    healthcheck:
      # Use "mongo" instead of "mongosh" before v5.0
      test: [ 'CMD', 'mongosh', 'admin', '--port', '${DB_PORT}', '--eval', "db.adminCommand('ping').ok" ]
      interval: 5s
      timeout: 2s
      retries: 20

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    env_file:
      - .env.local
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - ${EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:${DB_PORT}/admin?directConnection=true
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo-data:
